<a href="https://colab.research.google.com/github/lyj041214/ESAA/blob/main/YB0307_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [6]:
import numpy as np

A = np.random.random((5,3))
B = np.random.random((3,2))

print(A)
print(B)
print(np.dot(A,B))

[[0.95354506 0.68518424 0.96421648]
 [0.02737085 0.82949448 0.80359228]
 [0.41651258 0.13404214 0.56258799]
 [0.39956812 0.2159337  0.5019131 ]
 [0.15144752 0.02349279 0.27310465]]
[[0.23354552 0.75893529]
 [0.27939459 0.821894  ]
 [0.04726443 0.34362519]]
[[0.45970609 1.61815689]
 [0.27612994 0.97866379]
 [0.1613157  0.61959393]
 [0.17737069 0.65319095]
 [0.05484178 0.22809308]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
import numpy as np

A=np.arange(10)
A[(A>3)&(A<8)] *=-1
print(A)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

9
10

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2 #<<는 비트 연산자
Z <- Z
1j*Z #1j는 허수
Z/1/1
Z<Z>Z
```

legal
legal
illegal
legal
legal
illegal

In [9]:

vector1=np.array([1,2,3])
2 << vector1 >> 2


array([1, 2, 4])

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

nan
error
array([-9.22337204e+18])

In [12]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-12-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-12-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-12-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [11]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)
print(np.unique(Z1[np.isin(Z1,Z2)]))

[2 6 9 0 4 6 8 0 4 8]
[1 4 6 5 4 0 1 3 6 8]
[0 4 6 8]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False


In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)
#emath만 복소수 연산이 가능

<ipython-input-67-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [13]:
Z = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [ ]:
A=np.random.randint(10)
B=np.random.randint(10)
C=np.add(A,B)
D=np.negative(A)
E=np.divide(D,2)
F=np.multiply(A,E)
print(F)

-24.5


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [20]:
A=np.random.uniform(1,11,5)
print(A//1)

[ 4.  6. 10.  7.  7.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [21]:
A=np.random.randint(0,5,25).reshape((5,5))
print(A)

[[2 3 4 2 4]
 [4 1 1 4 4]
 [3 0 0 3 1]
 [1 1 1 4 4]
 [0 0 4 0 1]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [22]:
A=np.random.randint(0,20,10)
print(A)
print(np.sort(A))

[ 7  9  6 18  5 16  7 15 12 15]
[ 5  6  7  7  9 12 15 15 16 18]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [23]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

print(np.array_equal(A,B))

False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [24]:
cartesian=np.random.rand(10,2)*10
dist=np.sqrt(cartesian[:, 0]**2 + cartesian[:, 1]**2)
ang=np.arctan2(cartesian[:, 1], cartesian[:, 0])
polar = np.column_stack((dist, ang))
print(dist)
print(polar)

[ 8.93455347  5.78961191  8.89607225  6.78499637  2.93850665 11.89620153
  8.90606129 10.4538591   7.92001818  8.10488559]
[[ 8.93455347  1.06066873]
 [ 5.78961191  1.15692053]
 [ 8.89607225  1.01250318]
 [ 6.78499637  0.55476445]
 [ 2.93850665  1.17587105]
 [11.89620153  0.59016971]
 [ 8.90606129  1.07835007]
 [10.4538591   1.00924435]
 [ 7.92001818  0.16850568]
 [ 8.10488559  1.51989214]]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [25]:
Z=np.random.randint(0,10,10)
Z[Z.argmax()]=0
print(Z)

[1 5 8 0 1 6 9 0 4 4]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [28]:
Z = np.arange(100)
v = np.random.uniform(0,100)
dist=np.abs(Z-v)

min_index=np.argmin(dist)
Z[min_index]

56

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [36]:
Z = np.arange(9).reshape(3, 3)

for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [40]:
n = 3
p = 2
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),8)
print(Z)

[[0. 8. 0.]
 [0. 0. 0.]
 [0. 8. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [41]:
# column 1
Z = np.random.randint(0,10,(3,3))
print(Z)
Z[np.argsort(Z[:,0])]

[[5 9 6]
 [2 1 8]
 [4 7 4]]


array([[2, 1, 8],
       [4, 7, 4],
       [5, 9, 6]])

In [42]:
# column 2
Z = np.random.randint(0,10,(3,3))
print(Z)
Z[np.argsort(Z[:,1])]

[[4 2 7]
 [4 5 5]
 [8 1 8]]


array([[8, 1, 8],
       [4, 2, 7],
       [4, 5, 5]])

In [43]:
# column 3
Z = np.random.randint(0,10,(3,3))
print(Z)
Z[np.argsort(Z[:,2])]

[[8 7 1]
 [6 9 5]
 [6 7 7]]


array([[8, 7, 1],
       [6, 9, 5],
       [6, 7, 7]])